### PR TITLE
Updated sample code to reference the renamed xPhpProvison resource

### LINKED ISSUE #5: xPhp resource name needs to be updated to xPhpProvision  php in Wordpress sample configuration
When one installs the modules that are required by Wordpress configuration from powershell gallery, the resource name for xPhp has changed in the latest version of xPhp module , and the new name is xPhpProvision. The below configuration resource block needs to be updated to refer to the new resource:
Old version:
xPhp php
        {
            InstallMySqlExt = $true
            PackageFolder =  $Node.PackageFolder
            DownloadUri = $Node.Php.DownloadURI
            DestinationPath = $Node.Php.Path
            ConfigurationPath = $Node.Php.TemplatePath
            Vc2012RedistDownloadUri = $Node.Php.Vc2012RedistUri
        }

Proposed version:
xPhpProvision  php
        {
            InstallMySqlExt = $true
            PackageFolder =  $Node.PackageFolder
            DownloadUri = $Node.Php.DownloadURI
            DestinationPath = $Node.Php.Path
            ConfigurationPath = $Node.Php.TemplatePath
            Vc2012RedistDownloadUri = $Node.Php.Vc2012RedistUri
        }

For the repro have a VM with latest WMF 5.0 and run the following script:
# This Script installs the required modules for the WordPress Sample
# It uses the PowerShell Resource Gallery, see https://msconfiggallery.cloudapp.net/
# This requires WMF 5.  If you don't have WMF 5, Please install the modules manually.

Write-Host "Installing required modules..."
Install-Module xWebAdministration -MinimumVersion 1.3.2 -Force
Install-Module xPSDesiredStateConfiguration -MinimumVersion 3.0.1 -Force
Install-Module xMySql -MinimumVersion 1.0 -Force
Install-Module xWordPress -MinimumVersion 1.0 -Force
Install-Module xPhp -MinimumVersion 1.0.1 -Force

### PR DESCRIPTION
**Pull request by Dan1el42**
Fixes #5

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xwordpress/10)

### CODE REVIEW

**Comment by kwirkykat** [comment]
> �userNameNotUsed�
> There are a bunch of messed up chars in these two files now. It looks like these were the wrong kind of quote characters before and then something happened with the encoding and now they can't be decoded.
> If you copy the 'unknown' char you can Ctrl-F and replace it super easily.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwordpress/10#-:-KS3o3WdsSwCICxVhUBK:b-23nb72)_

**Comment by Dan1el42** [comment]
Thanks very much for catching these. PR updated.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwordpress/10#-:-KS5a7rY4o8mEESnOMZ3:bgfbl2b)_

**Comment by Dan1el42** [comment]
PR updated. I've inclued fixes for issue #7 and changed the MySQL version number to the currently latest.

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwordpress/10#-:-KS8_YBJPlnxmPfS2Tzd:bnfp4nl)_

**Pull request merged**
